import AppKit

public struct PasteboardSnapshot: Equatable, Sendable {
    public let items: [[String: Data]]

    public init(items: [[String: Data]]) {
        self.items = items
    }
}

public protocol PasteboardAccessing: AnyObject {
    var changeCount: Int { get }
    func snapshot() -> PasteboardSnapshot
    /// Replaces the contents with the text plus marker types. Returns the change count afterwards.
    func write(text: String, markerTypes: [String]) -> Int
    func restore(_ snapshot: PasteboardSnapshot)
}

public enum PasteboardMarkers {
    /// nspasteboard.org conventions. Clipboard managers skip items that carry these types.
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let all = [transient, autoGenerated]
}

public final class GeneralPasteboardAccess: PasteboardAccessing {
    private let pasteboard: NSPasteboard

    public init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    public var changeCount: Int {
        pasteboard.changeCount
    }

    public func snapshot() -> PasteboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            var contents: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    contents[type.rawValue] = data
                }
            }
            return contents
        }
        return PasteboardSnapshot(items: items)
    }

    public func write(text: String, markerTypes: [String]) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for marker in markerTypes {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(marker))
        }
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    public func restore(_ snapshot: PasteboardSnapshot) {
        pasteboard.clearContents()
        let items = snapshot.items.map { contents in
            let item = NSPasteboardItem()
            for (type, data) in contents {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        if !items.isEmpty {
            pasteboard.writeObjects(items)
        }
    }
}
