import AppKit
import QuothCore
import XCTest
@testable import QuothKit

private final class Recorder {
    var events: [String] = []
}

private final class FakePasteboard: PasteboardAccessing {
    let recorder: Recorder
    var changeCount = 10
    var contents = PasteboardSnapshot(items: [["public.utf8-plain-text": Data("old".utf8)]])
    var writtenMarkers: [String] = []
    var writtenText: String?

    init(recorder: Recorder) {
        self.recorder = recorder
    }

    func snapshot() -> PasteboardSnapshot {
        recorder.events.append("snapshot")
        return contents
    }

    func write(text: String, markerTypes: [String]) -> Int {
        recorder.events.append("write")
        writtenText = text
        writtenMarkers = markerTypes
        changeCount += 1
        return changeCount
    }

    func restore(_ snapshot: PasteboardSnapshot) {
        recorder.events.append("restore")
        contents = snapshot
        changeCount += 1
    }
}

private final class FakeKeystroke: PasteKeystrokePosting {
    let recorder: Recorder
    var isTrusted = true
    var onPaste: (() -> Void)?

    init(recorder: Recorder) {
        self.recorder = recorder
    }

    func postPaste() {
        recorder.events.append("paste")
        onPaste?()
    }
}

@MainActor
final class PasteInserterTests: XCTestCase {
    private struct Fixture {
        let recorder = Recorder()
        let pasteboard: FakePasteboard
        let keystroke: FakeKeystroke
        let inserter: PasteInserter

        init() {
            pasteboard = FakePasteboard(recorder: recorder)
            keystroke = FakeKeystroke(recorder: recorder)
            inserter = PasteInserter(pasteboard: pasteboard, keystroke: keystroke, sleep: { _ in })
        }
    }

    func testWritesPastesThenRestoresInOrder() async throws {
        let fixture = Fixture()
        let result = try await fixture.inserter.insert("Hello")
        XCTAssertEqual(fixture.recorder.events, ["snapshot", "write", "paste", "restore"])
        XCTAssertEqual(result, InsertionResult(strategy: .clipboardPaste, restoredClipboard: true))
        XCTAssertEqual(fixture.pasteboard.writtenText, "Hello")
        XCTAssertEqual(fixture.pasteboard.contents.items.first?["public.utf8-plain-text"], Data("old".utf8))
    }

    func testTemporaryContentCarriesTheMarkerTypes() async throws {
        let fixture = Fixture()
        _ = try await fixture.inserter.insert("Hello")
        XCTAssertEqual(
            Set(fixture.pasteboard.writtenMarkers),
            ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        )
    }

    func testSkipsRestoreWhenSomeoneElseWroteToTheClipboard() async throws {
        let fixture = Fixture()
        fixture.keystroke.onPaste = { fixture.pasteboard.changeCount += 1 }
        let result = try await fixture.inserter.insert("Hello")
        XCTAssertEqual(fixture.recorder.events, ["snapshot", "write", "paste"])
        XCTAssertFalse(result.restoredClipboard)
    }

    func testRefusesWithoutAccessibilityAndTouchesNothing() async {
        let fixture = Fixture()
        fixture.keystroke.isTrusted = false
        do {
            _ = try await fixture.inserter.insert("Hello")
            XCTFail("expected accessibilityNotGranted")
        } catch {
            XCTAssertEqual(error as? InsertionError, .accessibilityNotGranted)
        }
        XCTAssertTrue(fixture.recorder.events.isEmpty)
    }

    func testEmptyTextIsRejected() async {
        let fixture = Fixture()
        do {
            _ = try await fixture.inserter.insert("")
            XCTFail("expected emptyText")
        } catch {
            XCTAssertEqual(error as? InsertionError, .emptyText)
        }
        XCTAssertTrue(fixture.recorder.events.isEmpty)
    }

    func testRealPasteboardRoundTripOnAPrivatePasteboard() {
        let board = NSPasteboard.withUniqueName()
        defer { board.releaseGlobally() }
        let access = GeneralPasteboardAccess(pasteboard: board)
        board.clearContents()
        board.setString("original", forType: .string)

        let saved = access.snapshot()
        let count = access.write(text: "dictated", markerTypes: PasteboardMarkers.all)
        XCTAssertEqual(count, board.changeCount)
        XCTAssertEqual(board.string(forType: .string), "dictated")
        XCTAssertNotNil(board.data(forType: NSPasteboard.PasteboardType(PasteboardMarkers.transient)))

        access.restore(saved)
        XCTAssertEqual(board.string(forType: .string), "original")
        XCTAssertNil(board.data(forType: NSPasteboard.PasteboardType(PasteboardMarkers.transient)))
    }

    func testKeyCodeForVResolvesOnTheCurrentLayout() {
        XCTAssertNotNil(KeyCodeResolver.keyCode(for: "v"))
    }
}
